name: Tests

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faabric/base:0.0.4
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v2
      - name: "Python formatting check"
        run: black --check .
      - name: "C/C++ run formatting"
        run: ./bin/run_clang_format.sh .
      - name: "Check if there are any changes"
        run: git diff --exit-code
      - name: "Ping redis"
        run: redis-cli -h redis ping
      - name: "Create build dir"
        run: mkdir build
      - name: "Set up build"
        run: >
          cmake
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          ..
        working-directory: build
      - name: "Build tests"
        run: cmake --build . --target faabric_tests
        working-directory: build
      - name: "Run tests"
        run: ./bin/faabric_tests
        working-directory: build
